package user

const (
	UNKNOW_ERROR        = -1
	USER_CREATE_SUCCESS = iota
	USER_CREATE_FAILURE
	USER_UPDATE_SUCCESS
	USER_UPDATE_FAIULRE
	PASSWORD_CORRECT
	PASSWORD_INCORRECT
	USER_EXISTED
	USER_NOT_EXIST
	USER_DELETE_SUCCESS
	USER_DELETE_FAILURE
	AUTH_PASS
	AUTH_ERROR
	QUERY_PASS
	QUERY_FAILURE
)
